### ISSUE TITLE
For loops

### ISSUE THREAD

**Issue by Ryan-321** [ga-dc/try-ruby#1]
Ruby - 
for current_iteration_number in 1..100 do
   puts "Hello world, this is number #{current_iteration_number}"
end

Js - 
for (var i = 0; i < 100; i++) {
    console.log("Hello world, this is a number" + i);
}

They share the basic principle, but slightly different syntax.  Both doing the same thing.  Ruby looks like they go up by 1 as a default, though am sure there's a way to change this.  Ruby doesn't use the + to concatenate, just a space then variable. Statement is not in a block, but ended, by 'end'.  Seems like it was made to more readable and loose.  This will confuse me for awhile.

**Comment by jshawl** [comment]
:+1: yes ruby was designed with developer happiness in mind!
