### ISSUE TITLE
For Loops

### ISSUE THREAD

**Issue by mattficke** [ga-dc/try-ruby#10]
Ruby handles For Loops differently than other languages. There does seem to be a method similar to the more common for loop:

```
for number in array
  puts "This is the number: #{number}"
end
```

...but it looks like this alternative method is the preferred way of doing things in Ruby:

```
array.each do |number|
  puts "This is the number: #{number}"
end
```

I don't entirely understand why that is yet!

**Comment by jshawl** [comment]
oh yes.. and interpolation! :+1: 

`for` is very uncommon in ruby. I'm not sure why that is either..
