### ISSUE TITLE
Try ruby homework

### ISSUE THREAD

**Issue by chrislovett03** [ga-dc/try-ruby#11]
In JavaScipt, complex data types like arrays are created in similar ways to Ruby. In Ruby, you have more power to manipulate the data in your area with ease. For instance, you can quickly convert, reverse, and separate all parts of the array. 

Ex: 40.to_s.reverse --> Turn the integer 40 into a string, and then reverses the string. -->'04'

**Comment by jshawl** [comment]
:+1:
