### ISSUE TITLE
Mitchell Carroll's (try-ruby) HW

### ISSUE THREAD

**Issue by mitchellcarroll** [ga-dc/try-ruby#126]
**Differences:** 
- Ruby is more intuitive in regards to syntax of commands. There doesn't appear to be as many {} or (). 
- Ruby does not use a semicolon after each line. 
- Ruby sometimes uses ".." as a prompt when the system is requesting more information from the user. 

**Similarities:** 
- Both Ruby and JS have objects and functions.
- Both languages use relative and absolute paths to locate a file. 
- Both languages use for and while loops. 

**Thoughts on Ruby (so far):** 
I enjoyed the tutorial and thought that it appears at a very basic level to be a little easier to grasp. The syntax has been easier to read and write than javascript.

**Comment by AndyWhitley** [comment]
👍
