### ISSUE TITLE
Bedig Galladian HW

### ISSUE THREAD

**Issue by bgalladian** [ga-dc/try-ruby#127]
3 Differences:
    1.Different semantics
    2.Different Syntax
    3.Ruby seems more straight forward

3 Similarities
    1.Both have objects
    2. Both have arrays
    3. Both use similar characters (i.e brackets)

What I like:
So far, it seems much simpler and straight forward.  No real terminology to trip me up...yet!  Hopefully I will understand it better.

**Comment by AndyWhitley** [comment]
👍
