### ISSUE TITLE
Will Hawkins does Ruby

### ISSUE THREAD

**Issue by hawkins-will** [ga-dc/try-ruby#128]
Well hello there! I completed the thing.

Similarities between Javascript and Ruby:
- Both take Strings, Numerical Values, and Arrays
- Both have inherently built in mathematical methods
- Both are text based programming languages

Differences: 
- You don't have to request that Ruby return values. It just knows to.
- Converting Strings to Arrays and the reverse is incredibly intuitive
- Iterating through a variable and finding the first instance of a given input is simple

Statement:
From my (admittedly rudimentary) understanding of Ruby, it appears to be an incredibly intuitive language. The translation of Ruby Syntax to its English equivalent is more or less direct and it seems like it will be very easy to learn the Syntax. The logic behind it and Javascript seems essentially the same.

Comfort: 5/5
Completeness: 5/5

**Comment by nayana487** [comment]
👍
