### ISSUE TITLE
Fiona - Try Ruby

### ISSUE THREAD

**Issue by nfiona** [ga-dc/try-ruby#129]
- List 3 differences between Ruby and Javascript
 

1. Ruby is written in one line  (one function follows the other) or chaining method
2.  Calling a function in Ruby is simpler, using only a dot + the name of the function;
3.  The "to" functions, which is not available in JavaScript.

- List 3 similarities between Ruby and Javascript
 

1. A String needs to be wrapped between two quotation marks (single or double) and numbers can be  written as is.
2. Datas can be stored in an array in a variable in the same format as JavaScript array;
3. The use of square brackets

 
- What are your thoughts on Ruby so far? (2-3 sentences)

 Ruby is definitely a lot more simpler than JavaScript, for instance the function names are more semantic compared to JavaScript. This would make my life easier (hopefully this is not an uninformed optimism!). I enjoy Ruby so far.

**Comment by nayana487** [comment]
👍
