### ISSUE TITLE
Kay Ehni Ruby Levels 1-3 HW

### ISSUE THREAD

**Issue by ehnik** [ga-dc/try-ruby#130]
Differences between Ruby/JS:
--you can split a string based on lines in Ruby (of course you could do this in Javascript, but it would be more complicated as far as I know)
--some methods that require an argument in JS don't in Ruby (i.e. '.join' vs .join("")
--the print method in JS is completely different (prints to an actual printer)

Similarities between Ruby/JS:
--you can convert a string in to a number with a single method (parseInt in JS, to_i in Ruby)
--the sort method in ruby is basically the same as .sort() in JS
--they work with some similar data types--strings, integers, arrays

Ruby seems a bit closer to plain English and therefore a little simpler to write out. It seems like it may also have more methods that can be chained directly to a variable, which is great for efficiency. Looking forward to learning more!

**Comment by AndyWhitley** [comment]
👍
