### ISSUE TITLE
Try Ruby HW (Justin Shin)

### ISSUE THREAD

**Issue by Justin-Shin** [ga-dc/try-ruby#134]
**Differences:**
Strings in ruby are mutable whereas in JS they are not. Very interesting- something like "Justin".reverse wouldn't work in JS, you would have to apply a transformation and then set a variable to store the new string. In ruby it appears it runs the transformation on the string itself.

The sort function in ruby applies directly to the array and changes the array instead of creating an instance of the sorted array you can copy into a variable, also it appears that sort runs against the actual value of the number (if sorting numbers) instead of unicode point value, that is [1,2,30,10,3,20] sorts to [1,2,3,10,20,30] not [1,10,2,20,3,30] like it would in JS

Syntactical differences- piecing functions together are different

**Similarities:**
Data types are similar, strings and numbers as opposed to having strings, integers, shorts, longs, etc

Language is similar despite syntactical differences

It has similar functionality it seems, at least in a shallow sense

I don't like change.  Just kidding, I'm looking forward to learning more about this language and how it relates to JS (if it does)

**Comment by superbuggy** [comment]
👍 ES2015/ES2016 have some features that feel similar to ruby (ES6 'classes') `**` operator in ES2016
