### ISSUE TITLE
Nat Carter | Try Ruby 1-3

### ISSUE THREAD

**Issue by ghost** [ga-dc/try-ruby#135]
Comfort: 5 / 5
Completeness: 5 / 5

### 3 differences between Ruby and Javascript

- Ruby does not have keywords for variable declaration, whereas Javascript has var, let, and const.
- Ruby does not have type coercion; Javascript does.
- Ruby, unlike Javascript, allows you to omit the end-parentheses when calling methods.

### 3 similarities between Ruby and Javascript

- Both languages have variables.
- Both languages have arrays.
- In both languages, arrays are mutable, whereas strings are immutable.

### Thoughts on Ruby so far

So far, it looks like Ruby has quite a bit less syntactic sugar than Javascript. I suppose that's refreshing, although, at the end of the day, code is code. I look forward to learning more, especially about how hoisting and scope might be different in Ruby than in Javascript.

**Comment by amaseda** [comment]
:+1:
