### ISSUE TITLE
Laura G Try Ruby

### ISSUE THREAD

**Issue by laurkgol** [ga-dc/try-ruby#136]
List 3 differences between Ruby and Javascript
-You can change part of a string in one step (i.e. poem["toast"] = "honeydew" replaces the word toast with honeydew in the poem string.
-Print in Ruby functions the same as console.log in Javascript but you don't need (). 
-You can target lines in a string in Ruby

List 3 similarities between Ruby and Javascript
-Ruby and Javascript both use the format "target variable"."method"
-They both allow you to keep adding methods to the same line of code
-They both use [] to target something with in the variable 

What are your thoughts on Ruby so far? (2-3 sentences)
The syntax for Ruby seems very intuitive and simple compared to Javascript. It also seems to be able to pinpoint parts of strings without converting them to arrays first as you have to do in Javascript so overall it looks easier to use.

**Comment by AndyWhitley** [comment]
👍
