### ISSUE TITLE
Dan Lin Ruby

### ISSUE THREAD

**Issue by dlin2102** [ga-dc/try-ruby#137]
3 Differences:

1.  Ruby seems simpler in terms of syntax.
2.  It has a prompt (>), similar to the terminal's $ prompt.
3. It uses a fat arrow for responses to your entries.

3 Similarities:

1. They both have objects, arrays, and functions.
2. They both use relative and absolute paths.
3. They both have for and while loops.

Thoughts on Ruby (so far):
I really enjoyed the tutorial. It seems to be simpler than javascript but still retains the core concept.

**Comment by AndyWhitley** [comment]
👍
