### ISSUE TITLE
Collin O HW

### ISSUE THREAD

**Issue by cMoney667** [ga-dc/try-ruby#138]
Differences

-Seems a little bit easier and very close to human language.

-You can use a "!" at the end of an argument and it will permanently change what is stored at that value

-Can make a value or array a lot easier.

Similarities

-They both have the same data types

-syntax are almost the same

-easy to learn understand and write

I am excited to learn Ruby and how it will work with web, also if there is any connection with JS. I have used a few different programs when I was working that ran on ruby and i liked how quickly they worked.

**Comment by phantomhaircuts** [comment]
👍
