### ISSUE TITLE
TRY RUBY / HW / ISAAC DUARTE

### ISSUE THREAD

**Issue by Philocoder93** [ga-dc/try-ruby#139]
Differences: 
1. Ruby has a much simpler syntax than Javascript (at least ES5 js).
2. Ruby has slightly different loops (for example, the unless loop).
3. Ruby has fewer front end interaction features than js.

Similarities:
1. Still has objects and arrays, primitive data types etc.
2. Both are pretty accessible, nothing crazy esoteric yet.
3. Both are pretty widely used.

Thoughts: Ruby is the first language I ever coded in so it's a little weird coming back to it after so much js. The vastly simplified syntax is very nice though.

Comfort: 5/5 
Completeness: 5/5

**Comment by nayana487** [comment]
👍
