### ISSUE TITLE
for loops

### ISSUE THREAD

**Issue by rewarren** [ga-dc/try-ruby#14]
# Ruby: used to iterate an object. I read that the for loop isn't used as much in ruby, and instead the  .each method is preferred because the for loop does not create a new scope for the object whereas the .each method does.
# syntax:

for iterator in iterable_object
  # do something
end
#2 ex:

for number in (0..5)
  puts number
end

//JavaScript - used to iterate an object or block of code

//syntax:

for (statement 1; statement 2; statement 3) {
    code block to be executed
}

//ex:

 for (i = 0; i < 5; i++) {
    text += "The number is " + i";
}

**Comment by jshawl** [comment]
:+1: yes `.each` is super convenient!
