### ISSUE TITLE
TryRuby HW (Mike)

### ISSUE THREAD

**Issue by ghost** [ga-dc/try-ruby#140]
List 3 differences between Ruby and Javascript
- The exclamation mark (!) plays a role in Ruby
- Lines within strings can be separated. Ruby recognizes if a string is written on separate lines.
- You can have a mathematical operation with a string in Ruby: "text"*­3 = "texttexttext"

List 3 similarities between Ruby and Javascript
- Similar data types: strings, numbers, arrays
- Ruby uses methods with the same syntax: .method
- Ruby also throws an error when a wrong command is used

What are your thoughts on Ruby so far? 
- It has similar concepts to Javascript
- It seems to be an expansion of Javascript, allowing us to do things which wasn't possible in Javascript

**Comment by nayana487** [comment]
👍
