### ISSUE TITLE
Nyketha's Try Ruby Homework

### ISSUE THREAD

**Issue by Nykke** [ga-dc/try-ruby#142]
Similarities:
1) Uses Numbers, Math Operators, Strings, Objects, Arrays and Methods.
2) Can check the value of variable in the prompt the same way as JS in the console.
3) Uses Higher Order Functions. 

Differences:  
1) Unlike Javascript, Ruby gives you useful error messages, like git.
2) It is easier to convert strings with the "to" method in Ruby... methods in general seem much more simple in Ruby.
3) Stores variables differently, instead of "var", "const", "let", you can just type in the name of the variable and what it's equal to. Example "ticket = [12, 47, 35]"
4) Uses print and can change variables in an array by using a [] instead of the dot method

Ruby seems pretty straight forward. To get something it seems you type in very direct commands instead of going the roundabout as you do with JS. I'm excited in learning this language, it seems like one of the simpler ones to understand how things work explicitly.

**Comment by superbuggy** [comment]
>Unlike Javascript, Ruby gives you useful error messages, like git.
😆 
>Uses print and can change variables in an array by using a [] instead of the dot method
should be change variables in an ***array*** by using a [] instead of the dot method

👍  overall!
