### ISSUE TITLE
Lisa Burr - Ruby HW

### ISSUE THREAD

**Issue by laburr27** [ga-dc/try-ruby#143]
Lisa 3 differences between Ruby and Javascript:

1.  Don't have to use "var" to tell Ruby you are assigning a variable
2. Ruby is much more "plain language" than JS
3. Ruby directly prints outputs within the programming framework where JS needs to send output to somewhere like console.log

List 3 similarities between Ruby and Javascript:

1.  Both use quotes to denote strings
2. Both use basic operators (+, -, *, /)
3. Arrays are defined by using "[]"

What are your thoughts on Ruby so far? (2-3 sentences)

Ruby SEEMS to be pretty straightforward and much more user-friendly especially with the use of plain language syntax.  The compounding of actions in one line is interesting and I am looking forward to learning more.

**Comment by superbuggy** [comment]
👍
