### ISSUE TITLE
Try Ruby - Erica Norby

### ISSUE THREAD

**Issue by ericanorby** [ga-dc/try-ruby#144]
List 3 differences between Ruby and Javascript
- Javascript uses semicolons, Ruby does not
- Adding ! at the end of a method in Ruby will modify the original data
- Methods in Ruby that do not need arguments do not require parentheses

List 3 similarities between Ruby and Javascript
- They both use .length to obtain the length of a string
- They both use arrays
- They both use variables

What are your thoughts on Ruby so far? (2-3 sentences)
Conceptually, Ruby seems very similar to Javascript. The syntax looks simple and straightforward. I'm curious to learn how much freedom there is in Ruby as opposed to Javascript.

**Comment by phantomhaircuts** [comment]
👍
