### ISSUE TITLE
RODNEY CURL ( RUBY! )

### ISSUE THREAD

**Issue by rodneycurl** [ga-dc/try-ruby#147]
3 Differences 

1. The response kicks back a => (fat arrow) whenever there is a response
2. In ruby you type strings like to_s vs. in javascript you put strings in “ “. You can also convert values to integers by using to_i and also make arrays using to_a
3. You can create variables in Ruby by just using the name = without setting it with var like you have to in Javascript.

3 Similarities

1. Both Ruby and Javascript allows you to do equations (+, -, *, /, etc.)
2. Both Ruby and Javascript uses methods.
3. Both Ruby and Javascript allows you to use .length to determine the number of characters in a word.
4. Both Ruby and Javascript includes Numbers and Strings.

I think Ruby is awesome definitely a lot less code and everything seems to be a lot clearer. I can’t wait to learn more about Ruby!

All the best,
Rodney

**Comment by nayana487** [comment]
👍
