### ISSUE TITLE
Ben Shapiro - Ruby HW

### ISSUE THREAD

**Issue by pretorben** [ga-dc/try-ruby#148]
Similarities to Javascript:
1. The basic math functions have the same syntax.
2. There is a sort method for arrays.
3. Both languages can print to the console for testing purposes.

Differences to Javascript:
1. Multiplying a string in Ruby repeats it with each iteration concatenated to the next; in Javascript it returns NaN.
2. Ruby's sort method rearranges numbers in numerical order- 1, 2, 3, 10, 20, 30- instead of 1, 10, 2, 20, 3, 30 like Javascript.
3. It appears Ruby uses periods in place of parentheses in Javascript.

I like Ruby so far; some of the syntax is a little shorter than Javascript, but the functions are in the same ballpark.  My main concern so far is not mixing up the syntaxes between the two.

**Comment by superbuggy** [comment]
> It appears Ruby uses periods in place of parentheses in Javascript.
Ruby uses `.` for method calls, but this is an understandable conclusion

👍 good work!
