### ISSUE TITLE
Kevin Keller - Try Ruby

### ISSUE THREAD

**Issue by kkeller93** [ga-dc/try-ruby#149]
List 3 differences between Ruby and Javascript:
- When changing to a string, array, integer you do .to_s , .to_a, .to_i all respectively unlike in Javascript where it uses .toString or .parseInt
-  Updating text within Ruby seems much easier in comparison to Javascript (i.e. poem['toast'] = 'honeydew') and it replaces the word in the poem
- Parenthesis are not needed after calling a method and same with semicolons not being needed at the end of a line

List 3 similarities between Ruby and Javascript:
- When calling built-ins (i.e. .reverse or .length) it is called in the same manner
-  Assigning variables and creating the arrays is the exact same between Ruby and JS
-  Both languages are able to print into the console to be able to test the code better

What are your thoughts on Ruby so far? (2-3 sentences)
So far, it seems that Ruby will be a much simpler language in comparison to javascript since we have learned the basics to JS it will make Ruby simpler to understand. It also seems that there will be more versatility in Ruby when calling methods within methods

**Comment by phantomhaircuts** [comment]
👍
