### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by silviascript** [ga-dc/try-ruby#15]
In comparison to JavaScript, the Ruby syntax is simple and easier to understand. Both JavaScript and Ruby have arrays that are similar to each other. In JavaScript's object array function and Ruby's class array methods have different syntaxes. For example, if I wanted to find the index of an element in both the arrays, I would need to the following below.

In JavaScript:

``` javascript
var array = [1, 2, 3, 4];
array.indexOf(3);
// => 2
```

In Ruby:

``` ruby
array = [1, 2, 3, 4]
array.index(3)
// => 2
```

**Comment by jshawl** [comment]
:+1:
