### ISSUE TITLE
i want a poignant guide, too

### ISSUE THREAD

**Issue by xgironx** [ga-dc/try-ruby#151]
*** List 3 differences between Ruby and Javascript**
1. Ruby has a Poignant Guide.   Javascript appears to care less for my feelings.  
2. The use of brackets as search delimiter is new to me.
3. Javascript distinguishes between comparison operators that test value & datatype; Ruby, tests both w the double-equal where js does not
4. Ruby is sort of "strongly typed” … prevents runtime errors, does not catch errors at compile time.  Equestrian tells me that if it were really strongly-typed it would catch some errors at compile & runtimes.  I found “duck typed” but don’t understand it yet.
5. I have to understand how Ruby uses pipe (|).  I don’t, yet.   
6. Ruby doesn’t care for semicolons, i, personally, think they're ok
7. I might come to like the conciseness, a la:
    1. to_i instead of parseInt
    2. to_a
    3. to_s
8. "Symbols" seem cool
9.  Ruby likes chaining like jquery and some of the DOM-related js we've done

*** List 3 similarities between Ruby and Javascript**
1. Both are weakly-typed, although it depends what I read, like on “duck typed”
2. Arrays and other object types have methods, like File.* and Dir.* and array slice, splice, split
3. Ruby has to_* functions to convert datatypes, and js has “type coercion”
4. Both Ruby & js use similar scope thingies — “this” an “self”
5. Both languages allow passing functions as variables

*** What are your thoughts on Ruby so far? (2-3 sentences)**
1. I want my own Poignant Guide.
2. I think I might enjoy Ruby’s syntax after working with it. It appears to have some elegance and concision that will appeal.
3. Seems like Ruby might look more like Java OO code that I’ve seen, js looks like a different animal, at least, especially in es5, while es6 with “class” and “new” start to look like code I’ve seen at work and read about in “Head-First Java”
4. I think I like “this” better than “self”, sounds smarter & funner, less self-absorbed, self-involved, 
5. as with jquery, i haven't worked with chaining commands enough, first impression is it's tough to know who's coming and who's going.

**Comment by superbuggy** [comment]
👍 nice Jay!
