### ISSUE TITLE
Savraj Singh

### ISSUE THREAD

**Issue by SavrajSingh** [ga-dc/try-ruby#152]
3 Differences:
While they both have coercion, ruby is not dynamically typed. 
It seems like there is no need for ending semicolons.
There seems to be no function declaration.

3 Similarities:
The first similarity that I was the fact that they both use the same primitive data types.
The second thing is the use of the dot product for methods.
They both have coercion. 

So Far:
The language is very close to JS and I like the fact that this website makes it feel like the CLI.

**Comment by amaseda** [comment]
In what sense does Ruby have coercion? Javascript acts differently than Ruby in this respect.
