### ISSUE TITLE
Aaron Andrews

### ISSUE THREAD

**Issue by andrews94** [ga-dc/try-ruby#153]
Similarities:

Both have simple math functions with similar syntax.

Both use methods

Both use the same syntax for arrays and strings

Differences:

Ruby does not use Var to define variables.
The use of semicolons is not needed like it is in javascript
Ruby has a reverse command

I like ruby so far it is interesting and seems to have more functionality and easier syntax then javascript.  I felt like I had a good understanding of javascript so I am hoping it will be the same for ruby.

**Comment by superbuggy** [comment]
javascript has an array reverse method too, actually!

👍 overall!
