### ISSUE TITLE
Wes Coffay ruby

### ISSUE THREAD

**Issue by justwes2** [ga-dc/try-ruby#154]
Similarities: 
Still works with values and operators. 
Tool to manipulate data (in the good understand it way not the bad change it way)
So far seems syntactically similar to js 

Differences:
More concise
Focus on useablity
Does more to present data effectively 

Thoughts:
So far ruby seems similar to js. It is more concise but I think that as we work with more complicated functions that will change. Overall it seems functionally similar.

**Comment by amaseda** [comment]
:+1:
