### ISSUE TITLE
Try Ruby HW - Elena Santana

### ISSUE THREAD

**Issue by fanelenan7** [ga-dc/try-ruby#155]
Differences:

Ruby is very user-friendly (so far).
Easier to remember syntax.
Ruby is purely object oriented language.
snake_case

Similarities:

Same data types, different names.
Logic is very familiar.
Methods are capable of doing similar things to functions (and methods) in JS.
Operators are the same. If I had to guess ** that is the same as Math.pow() actually made it's way to JS from Ruby.

I feel like it seems a lot easier than JS to me, but at the same time I know that it's probably because we already got a good grasp on the JS and it's logic. I find myself constantly comparing Ruby to JS and looking for familiar things and things that are different.
I took me 2 hours to get Fizzbuzz working right for the first time during the pre-work. The same thing had taken me 2 minutes with Ruby, but only because I already knew how to do it with JS.

**Comment by amaseda** [comment]
:+1:
