### ISSUE TITLE
Try Ruby - Vince Campanale

### ISSUE THREAD

**Issue by vincecampanale** [ga-dc/try-ruby#156]
Similarities Between Ruby & JS:
1)  Methods performed on objects with '.' notation. (i.e. `"string".method`)
2) Method chaining
3) You don't have to declare the type of the variable before you save something into it. 

Differences Between Ruby & JS:
1) Methods invoked without parentheses (i.e. `array.sort` vs. `array.sort()`)
2) Lots of extra handy methods built into Ruby. (i.e. `array.max`, "string".reverse, targeting a specific word in a string with brackets, and more) 
3) Error messages are more informative. 

Thoughts on Ruby:

Really liking what I see. I was impressed with `.reverse` and `.max` because I know how much extra code it takes to implement those in Javascript. When we targeted a specific word in the string just by saying `string['word']`, I got even more excited.  Ruby is powerful.

**Comment by amaseda** [comment]
:+1:
