### ISSUE TITLE
Dominick Ruby HW

### ISSUE THREAD

**Issue by dhouston14** [ga-dc/try-ruby#158]
3 similarities:
Both are easy to set variables syntactically
The use of key:value pairs.( ie car.make ...)
Both use vim and print to the console for usability.

3 differences:
Using parse int compared to using to_i creating integers.
Using def when creating functions in ruby compared to functions in javascript
== in ruby to determine if 2 values are equal or (TRUE) compared to === in javascript

Great to learn and dive into as a new programming language. Interested in how ruby is used for database collection and its general functionality.

**Comment by phantomhaircuts** [comment]
👍
