### ISSUE TITLE
Gill Ruby HW

### ISSUE THREAD

**Issue by 585873** [ga-dc/try-ruby#159]
Similarities: 
Functions in JavaScript are the same as methods in Ruby. 
Both Ruby and JavaScript have Arrays, which are more of less logically the same;
JavaScript, like Ruby, can be object-oriented, meaning that objects, their associated methods/functions, can be neatly contained.

Differences: in JavaScript you write typeof and then then the object; in Ruby, you append .class to the end of the object.
One big difference between Ruby and JavaScript is the falsey-ness of certain values.
Ruby is front-end programming language and java is back-end.

Ruby seems to be more straight forward than Java and seems much more doable than java since I a not very comfortable with java.

**Comment by phantomhaircuts** [comment]
👍
