### ISSUE TITLE
ruby hw

### ISSUE THREAD

**Issue by pootsmagoots** [ga-dc/try-ruby#161]
Comfort 4/5
Completeness 4/5
-Three differences

Ruby calls an object a hash 
javascript is a client side language where Ruby is server side
Ruby does not use semicolons
functions are defined in Ruby for example def say_hello(num1,num2)

Three similarities
Both languages use variables.
both are object orientated programming
Both seem similar, use of functions, objects etc. Just are written a bit differently

Thoughts on ruby

Ruby seems very similar to JS. I do think syntactically it is a little more confusing for me to comprehend. But I also think this is a very powerful language and it's benefits to learning are just as important to JS. It also seems to have a little Python flavor to it as well, which i find rather interesting.

**Comment by superbuggy** [comment]
javascript is a client side language where Ruby is server side
> the js we've been writing is client-side, but node is server-side js

> Both languages use variables.
True, but I think all programming languages have variables. in ruby you don't need a keyword like `let`, `const`, or `var` to declare a variable

It very much does have a python flavor!

👍  overall
