### ISSUE TITLE
Ruby-Habtamu abere

### ISSUE THREAD

**Issue by HabRonan** [ga-dc/try-ruby#162]
Javascript is a front-end language where as ruby is a back-end language

syntactic difference-the way you reference things like variables, classes, objects, hashes and so on.

Similarities

-both are interpreted instead of compiled
-Both are OOPL- both languages are using an object.
-Semantics of the language are almost the same

Thoughts

1. That it’s a great programming language, the fact that it’s open source and it has a syntax that I can read and understand easily
2. it’s a OOPL. Everything is an object.

**Comment by amaseda** [comment]
:+1:
