### ISSUE TITLE
Malcom Johnson Try Ruby

### ISSUE THREAD

**Issue by malrese1** [ga-dc/try-ruby#163]
Differences between Ruby and Javascript:
No var for a variable.
No ending semicolons.
Parenthesis are not needed after calling a method.

Similarities between Ruby and Javascript:
Both languages are able to print into the console. 
Ruby uses periods in place of parentheses unlike Javascript.
Both use basic operators. 

Ruby is much more user- friendly

**Comment by AndyWhitley** [comment]
👍
