### ISSUE TITLE
Try Ruby HW - Chris Wightman

### ISSUE THREAD

**Issue by cjwightman** [ga-dc/try-ruby#164]
Ruby follows much of the same logic as Javascript. The functions, or methods seem much more semantic and seem to enable cleaner more readable code.

I would liken javascript to Python in how fickle it is with punctuation and syntax whereas Ruby feels like it is focused more on the power and simplicity of the language. Definitely get the feeling that Ruby was designed to make coders happy in that there are many pre-constructed methods. It's my understanding that Ruby is a back-end language and I'm looking forward to seeing how it is applied to back-end resources and data sources. Javascript is powerful and has significant impact on the user experience but it is a bit more laborious than Ruby from what I can tell thus far.

**Comment by phantomhaircuts** [comment]
👍
