### ISSUE TITLE
Clements-Try Ruby

### ISSUE THREAD

**Issue by sdkclements** [ga-dc/try-ruby#165]
Diff: Played around with ruby a bit before and it seems like more of a traditional oop language compared to JS. Ruby seems to have better documentation, or rather different because it doesnt worry so much about front end management like jquery.
Sim: It has many of the same data types, and it also has similar methods on objects/arrys/classes etc, but theyre seems to be a bit more of them- ruby enumerable methods.

I am very excited to take a step back and work on OOP for a while and really understand it so when we come back to javascript i can handle it better. Not having to check chrome console all the time will be freeing.

**Comment by amaseda** [comment]
:+1:
