### ISSUE TITLE
Taylor Scott Ruby HW

### ISSUE THREAD

**Issue by taylorscott91** [ga-dc/try-ruby#166]
List 3 differences between Ruby and Javascript:
-Syntax! Lots of periods in Ruby, and no semicolons.
-Don't need to use "var" to declare a variable.
-Much different/easier to use methods of data manipulation.

List 3 similarities between Ruby and Javascript:
-Both are object oriented programming!
-Both can use similar math functions.
-Both use variables/functions to manipulate data.

What are your thoughts on Ruby so far? (2-3 sentences)
-Doesn't seem too difficult compared to JS! Just gotta learn the syntax. Looking forward to learning more about it.

**Comment by AndyWhitley** [comment]
👍
