### ISSUE TITLE
Erica Andersen's 'Try Ruby' Homework

### ISSUE THREAD

**Issue by ericacomfort** [ga-dc/try-ruby#17]
## Functions/Methods

Functions in JavaScript = methods in Ruby. These are both ways to create actions. However the syntax, for declaring a Javascript function and a Ruby method, differs. One example: 
#### Ruby

``` ruby
def sample_func
  puts "Hello World"
end

sample_func
```
#### Javascript

``` javascript
function sample_func() {
  console.log("Hello World");
};

sample_func();
```
### Additionally...

Some Ruby methods only work on certain types of values. Ruby is awesome though and has different types of "to" methods to easily convert the values you're working with.
- `to_s` converts values to strings.
- `to_i` converts values to integers (numbers).
- `to_a` converts values to arrays.

**Comment by jshawl** [comment]
:+1: Excellent formatting in this issue!!! :star2:
