### ISSUE TITLE
Try ruby

### ISSUE THREAD

**Issue by sonnykbp** [ga-dc/try-ruby#188]
**Differences:**
- Methods can be chained in a single line
- Different syntax
- Ruby is sever side, JS is more client side language 

**Similarities**
- Recognizes different data types i.e string vs. numbers
- Uses dot notation for methods
- Certain methods only work on certain data types

**Thoughts on Ruby**
So far it doesn't seem to be too challenging to transition into Ruby. Since both are object orientated languages, the logic and function/methods should be similar. But now we'll have to learn a whole new set of syntax specific to Ruby.

**Comment by superbuggy** [comment]
👍
