### ISSUE TITLE
Scott gave ruby a try

### ISSUE THREAD

**Issue by scottpiercew** [ga-dc/try-ruby#189]
List 3 differences between Ruby and Javascript
    * Ruby uses a fat arrow for responses to entries
    * .length can be called on a string but after the parentheses 
    * An exclamation mark prevents a command from making a copy of an array and instead creates the change to the array attached.

List 3 similarities between Ruby and Javascript
    * You can store information in a variable.
    * Arrays are used.
    * Square brackets are used for an array.

What are your thoughts on Ruby so far? (2-3 sentences)
    * Ruby has some straight forward functions like being able to easily switch information between a string and an integer. Ruby provides more direct ways to manipulate data stored in an array.

**Comment by superbuggy** [comment]
👍
