### ISSUE TITLE
Try-Ruby 

### ISSUE THREAD

**Issue by tarkzc** [ga-dc/try-ruby#191]
List 3 differences between Ruby and Javascript

1)  Methods seems more dry in Ruby
2) Syntax is not very similar (Objects & Hash)
3) In Ruby variables can be created without writing var 

List 3 similarities between Ruby and Javascript

1) Similar structure ( Arrays, variables, methods etc..)
2) Similar data types (numbers, strings)

**Comment by superbuggy** [comment]
👍
