### ISSUE TITLE
Ruby/Js

### ISSUE THREAD

**Issue by Fitssum** [ga-dc/try-ruby#192]
Differences
Js
1 - A front-end language (interacts with the browser)
2 - Complicated (in terms of syntax)
3 - with limitations
Ruby
1 - A back-end language (interacts with server)
2 - Much simpler syntax. Variables don't need to be declared for eg.
3 - More powerful and more possibilities (such as in the lesson about reversing texts, changing positions of lines, reordering variables...)
Similarities
1 - Both are object oriented programming languages
2 - Both use arrays
3 - Both use single and double quotes to form strings

**Comment by superbuggy** [comment]
👍
