### ISSUE TITLE
Bao's first impression on Ruby.

### ISSUE THREAD

**Issue by BaoPham92** [ga-dc/try-ruby#193]
Difference: 

1. Ruby seems to recognize and run mathematical values after a arrow sign.

2. It seems like we can using mathematical operations with strings. If I were to use my three letter name "Bao"*5, it'd result as "BaoBaoBaoBaoBao".

3. Ruby also carries a set of different methods we are able to use. Like, ".reverse" on strings to result our "name" backwards and every variables containing paragraphs even. The only thing is, you cannot use this on numeric values. Another example of a method different from what we use in Javascript is ".to_s.reverse". So, if you were to use numerical values for an example "100" (100.to_s.reverese) this will be "=> 001".

Note how the method was printed:
- I don't remember if i have actually seen "_" underscore character being used as writing out a pre-rendered method in Javascript either. 

- Not just this method, but the last one ".reverse" and ".length" as well seems to be pretty straightforward and brief about what the method actually does. ".to_s.reverse" (".to" indicating what after the "_" underscore) and ("s" indicates "String") thus the process of turning the numerical value into a string. There are other selector types other than "s" too.  "i" for integers, and "a" for converting values to arrays.

4.  Using ".max" option for array to find the highest value. ([1, 9].max) => 9.

5. "!" indicates directly interacting with a certain method. (ticket.sort!) "sort" => ordering values in a variable "method".

6. You're able to directly change a specific string of a variable by targeting a string of choice incased in a open/closed [] brackets. (yourVariable[YourChoiceOfStringToTarget].

similarities:

1. Using their operators finding new values for math in what seems to be a console on that site? 
Yeah it does. Anyways its pretty similar to how Javascript/console would use them.

2. A string is a key term and property just like Javascript. 

3. It also seems we can access functions of pre-rendered methods like "reverse" and "length"

4. Ruby seems to carry object containers array as well.

5. Ruby uses variables to store data using unique identifiers but without the need to define a "var".

Impressions? 

Well, seems rather hands down brief and clear when using methods and interactions with objects or variables which is welcomed for me. Great. Ruby has a bit of different approaches when it comes to using different "types" for conversions and selectors, which is fine seeing as how simple it is so far attempting the instructed number of levels as a introductory into the language. So far, it seems fun to use. You can do some interesting and creative uses or even for the fun part of it, tricks with even something simple as texts.

**Comment by superbuggy** [comment]
Nice!
