### ISSUE TITLE
AntwanaW HW

### ISSUE THREAD

**Issue by Antwana** [ga-dc/try-ruby#194]
Three similarities between ruby and javascript is that they both have arrays, variables, strings and number. You can also convert a thing to a number and a number to a string. simple math seems the same as well.

The syntax used to convert numbers to strings and strings to numbers is different. Also it seems you can turn a group of lines (like the poem) into an array with one command.  You can also rearrange the stings easily.

I like that there are similarities to javascript because it should be easier to learn. The syntax so far doesn't seem difficult.

**Comment by superbuggy** [comment]
👍
