### ISSUE TITLE
Mark - Try Ruby

### ISSUE THREAD

**Issue by mjm5vp** [ga-dc/try-ruby#195]
1) Three differences would be the syntax for ruby is much more compact, Ruby gives an output for ever command on the next line, and Ruby is more for the back end than the front end.
2) Three similarities would be that they have many of the same basic types such as numbers, strings and arrays, they both use methods on top of types and they can manipulate types in similar ways.
3)  Ruby seems to have a very simple syntax which makes it easier to understand.  I like how it has many predefined methods that do simple tasks that would take much longer in javascript.  I'm having trouble understanding exactly how and where it will be applied in web development yet however.

**Comment by superbuggy** [comment]
> Ruby gives an output for ever command on the next line

In `pry`, only

> Ruby seems to have a very simple syntax which makes it easier to understand. I like how it has many predefined methods that do simple tasks that would take much longer in javascript.

I love this also.

👍
