### ISSUE TITLE
Intro Ruby

### ISSUE THREAD

**Issue by AskForTheWolf** [ga-dc/try-ruby#197]
Differences: less structured, different commands, print instead of alert or console

Similarities: calling functions (.reverse), creating arrays.  Similar syntax sometimes.

Thoughts:
I like it.  It's intuitive, simple, and powerful.  I know it'll get harder but so far it's nice.

**Comment by superbuggy** [comment]
👍  You might argue Ruby's type system makes it more structured, but the syntactical structures are often not marked with symbols.
