### ISSUE TITLE
Jessica Marie Barre

### ISSUE THREAD

**Issue by jessamarie** [ga-dc/try-ruby#198]
Create an issue on this repo containing the following...

**List 3 differences between Ruby and JavaScript**
1. The method calls differ. In JS you have to attach a () even with 0 arguments, but with Ruby you only need the method name. (Ex: ['a','b','c']. sort() vs ['"a", "b", "c"]. sort
2. Ruby has the '!' which allows you to change the variable being manipulated
3. In Ruby you can access and modify a string with string['str'] which gives you the first location of 'str'. In JS you can only use indices.

**List 3 similarities between Ruby and Javascript**
1. They both have variables
2. They both have similar BIFs (max, sort, join, etc)
2. They both have data types (strings, arrays, numbers, etc) that function similarly

**What are your thoughts on Ruby so far? (2-3 sentences)**
It doesn't seem so hard yet. I have gotten to the Hashes section which seems to have the most differences from JS so far.

**Comment by juancgarcia** [comment]
👍
