### ISSUE TITLE
Jacob Greenwald HW

### ISSUE THREAD

**Issue by jacobg1** [ga-dc/try-ruby#199]
Similarities:
Both languages allow you to assign values to variables and access them later.
Both contain arrays, integers, strings, key / value pairs etc.
Both have methods that you can perform on arrays such as .length

Differences:
Ruby allows you to make copies of information or directly effect it with the ! operator.
Ruby has something called hashes which are contained in curly braces.
Ruby allows you to access values in an array and attach a value to it with the : operator.

Thoughts:
At first glance ruby seems to be relatively less confusing than JavaScript but seems to have a lot of different functions.

**Comment by juancgarcia** [comment]
👍
