### ISSUE TITLE
Ruby syntax

### ISSUE THREAD

**Issue by jeffjones89** [ga-dc/try-ruby#2]
Ruby looks to have been created in a way that's more closely related to english. 

I did find the use of [ ] notation to search and replace to be something that seems very useful. Being able to look at a large block of information and use one command to search for that information is quite valuable. 

I also thought the symbol methodology of storying the symbol once rather than multiple times in the document to be quite interesting as well.

**Comment by jshawl** [comment]
:+1: yes ruby was designed with developer happiness in mind!
