### ISSUE TITLE
Matt Filbert: First Impressions of Ruby

### ISSUE THREAD

**Issue by mattcfilbert** [ga-dc/try-ruby#201]
Similarities:
- Both have many of the same types of variable values (strings, integers, arrays, etc).
- Both have built-in methods that you can use on variables (such as ".length").
- Both use "=" for assignment 

Differences:
- Ruby has a better understanding of arranging numbers in arrays (sorts by size of number rather than sorting the numbers "alphabetically").
- Ruby offers more precision for users to directly alter variables (such as turning lines of a long string into separate pieces of an array, or using "!" to make permanent changes when invoking methods).
- Ruby is more clear about the reasons for errors than JS.

First impression:
Ruby comes with more out-of-the-box methods and control than JS and feels more intuitive.

**Comment by AndyWhitley** [comment]
👍
