### ISSUE TITLE
Alex W Ruby HW

### ISSUE THREAD

**Issue by awandres** [ga-dc/try-ruby#204]
Differences 

- Ruby syntax seems to be more direct, focusing less on parameters and more on overall function
- The ! command seems useful, especially since (im assuming) it can be applied to any method, as kind of its own 'flexible' operator
- Mostly done via command line (maybe?)

Similarities

- Strings, numbers, and arrays seem to function mostly the same
- Methods can be strung together to make complex tasks
- Has some of the same basic operations as JS

Overall -
Honestly, as of now, I don't have a good grasp of the uniqueness of Ruby

**Comment by juancgarcia** [comment]
👍
