### ISSUE TITLE
Try Ruby (Jonathan Polakoff)

### ISSUE THREAD

**Issue by jdpolakoff** [ga-dc/try-ruby#205]
**List 3 differences between Ruby and Javascript:**
1) Ruby has some different methods compared to Javascript, such as "reverse."
2) Ruby methods can be called without the "()" used in JavaScript to denote parameters. 
3) Ruby methods called with an "!" transform an array, while those called without the "!" create a copy of an array containing the transformed values. This is not a feature of JavaScript methods.

**List 3 similarities between Ruby and Javascript:**
1) Both languages use "=" to assign values to variables.
2) Both languages are comprised of data types including numbers, strings and arrays. 
3) Both languages use the ".length" method to calculate the length of a string.

**What are your thoughts on Ruby so far? (2-3 sentences):**
Ruby seems to take more plain english commands than JavaScript, and also seems to have a somewhat simpler set of syntax rules. I'm excited to learn more.

**Comment by AndyWhitley** [comment]
👍
