### ISSUE TITLE
Charles Cox Ruby Tutorial

### ISSUE THREAD

**Issue by cwcox** [ga-dc/try-ruby#206]
Differences:
Ruby emphasizes interacting with databases and file systems and has specific methods/functions to perform these actions
Ruby is more "lightweight" when typed, i.e. fewer characters are needed to perform similar tasks.
Ruby appears more focused on the effectiveness of the user, not the effectiveness of the computer reading the code.

Similarities:
There multiple ways to accomplish the same thing in both languages.
Both include function and OOP elements
"." serves a similar purpose in both languages for attaching methods to objects.

First Impressions
I had done this tutorial before, but didn't remember how much you can accomplish in one line of code.  I prefer the python philosophy of having one best way to do something, but am interested in seeing why ruby has become such a popular language in web development.

**Comment by juancgarcia** [comment]
👍
