### ISSUE TITLE
Try-Ruby ( Josue Rosales )

### ISSUE THREAD

**Issue by jhosuedeveloper** [ga-dc/try-ruby#210]
**List 3 differences between Ruby and Javascript**

Ruby has more easy to understand functions
Ruby has prebuilt functions for almost everything
Syntax is more logical and easier for Ruby

**List 3 similarities between Ruby and Javascript**

Similar operator signs for assigning
similar syntax for arrays
they both have conversion types

**What are your thoughts on Ruby so far? (2-3 sentences)**

Ruby seems interesting, I have a feeling that is has a lot of prebuilt functions that javascript lacks.
Ruby seems more easy to understand, looks very logical up to this point.

**Comment by AndyWhitley** [comment]
👍
