### ISSUE TITLE
Ruby and Js..

### ISSUE THREAD

**Issue by ghost** [ga-dc/try-ruby#211]
3 DIFFERENCES:
Ruby is a back-end language, Js is a front-end language
Ruby use methods already built in.
; semicolons are not mandatory in Ruby.

3 SIMILARITIES:

RUBY AS JSS use variables and arrays.
Ruby as Js uses methods
Ruby and Js are Object oriented programming languages.

I think Ruby is a more friendly language than Js, and sometimes easy to use. Methods already built in the program are very helpful.

**Comment by AndyWhitley** [comment]
👍
