### ISSUE TITLE
Trying out Ruby

### ISSUE THREAD

**Issue by perryf** [ga-dc/try-ruby#213]
3 Differences...
-You don't need var/let to declare variables
-There seem to be more built in methods on strings, like reverse, capitalize, etc
-It reads more like plain English

3 Similarities...
-You still have most of the same types - strings, numbers, arrays, etc
-You can still do if/else statements
-Loops seem similar

My thoughts...
There seem to be many different ways to do the same thing, like looping through something.  This will probably be good in the long run, but it makes it hard to memorize stuff off the bat.  Ruby seems to read a little easier which may make other people's code easier to digest.

**Comment by AndyWhitley** [comment]
👍
