### ISSUE TITLE
try-ruby (Timothy Gafvert)

### ISSUE THREAD

**Issue by TimGafvert** [ga-dc/try-ruby#214]
**List 3 differences between Ruby and Javascript:**
_Ruby seems to have more straight-forward and easy to use methods. Ruby seems more powerful and flexible. Ruby is a bit more forgiving when you mix types of variables._

**List 3 similarities between Ruby and Javascript**
_They both handle variables similarly. They both have their limits about what operations you can perform on certain variable types. They both have useful methods built in._

**What are your thoughts on Ruby so far? (2-3 sentences)**
_I like Ruby a lot so far. It seems simple and clean and easy to use._

**Comment by juancgarcia** [comment]
👍
