### ISSUE TITLE
Ruby Reflections (Liz Jewell)

### ISSUE THREAD

**Issue by lizardbird** [ga-dc/try-ruby#215]
**List 3 differences between Ruby and Javascript**

- Ruby will accept math operators and logic with strings where as Javascript will not. For example: "Liz" * 5  => "LizLizLizLizLiz" in Ruby, yet returns "NaN" in Javascript. 
- Ruby returns more descriptive errors which can help you learn and debug more quickly
- OMG Ruby will allow you to edit/access one piece of a string by it's plain language term. For example, when we typed poem['toast']='honeydew' it changed only the word toast to honeydew. That was pretty cool. 

**List 3 similarities between Ruby and Javascript**

- Both use object oriented programming, where the main elements are forms of data vs. actions.
- Both languages use methods on the objects, with a few key built-in methods like .length, etc.
- Both seem to have the ability to log or print the results of functions in a "console" so you can see what you are doing. 

**What are your thoughts on Ruby so far? (2-3 sentences)**

I like the short, plain language names for the built in methods. For example, instead of parseInt(item), I can simply use item.to_i. I appreciate that you can call methods without some of the extra characters [like how in JS you have to use empty parentheses to call a function ()]. I'm looking forward to learning more, including best use cases for Ruby!

**Comment by AndyWhitley** [comment]
👍
