### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by robertbenjamin** [ga-dc/try-ruby#22]
## Variables

In Ruby, running a method `variable.sort!` on a previously declared variable actually changes the contents of the variable, whereas in Javascript, you'd have to explicitly set your variable to the sorted version: `var variable = variable.sort()`.

Additionally (not really related to variables), Ruby method seem to be much more 'intelligent' so far — things like `lines.to_a` would be pretty complex to implement in Javascript (at least with my current knowledge of it).

**Comment by jshawl** [comment]
:+1: some js methods do mutate the instance:

`variable.shuffle()` for example
