### ISSUE TITLE
ruby hw - ruby vs javascript

### ISSUE THREAD

**Issue by adrianshep** [ga-dc/try-ruby#23]
In terms of functions/methods, there's a marked difference. JS requires precisely spelled-out commands in language that's opaque to new users, while Ruby only needs a basic word or two in the conversational English to understand what it's being asked to do. On top of which, chaining seems to allow Ruby the ability to execute in one line of code what would take JS several discrete functions and many lines to accomplish. So, at the outset, Ruby appears to be built for speed and convenience of programming.

**Comment by jshawl** [comment]
:+1: yes definitely was designed with convenience in mind!
