### ISSUE TITLE
Comparing Javascript and Ruby

### ISSUE THREAD

**Issue by walter-0** [ga-dc/try-ruby#25]
For loops in Javascript require the counting variable specified in each of the three fields, whereas Ruby only requires it specified once.

JS
for (i = 0; i < 50; i ++) {
  console.log( "Hello world, this is number" + [ i ] )
}

Ruby
for i in 1...50 do
  puts "Hello world, this is number #{ i }"
end

**Comment by jshawl** [comment]
:+1: or even `50.times do |i|` ...
