### ISSUE TITLE
Alex Bannon hw

### ISSUE THREAD

**Issue by alexbannon** [ga-dc/try-ruby#26]
.to_a, .to_i, and .to_s seem so ridiculously easy. While js has .join, .split, etc (kinda auto-iteration), ruby seems more straightforward already.

But there are some things that seem worse than js. For example, ticket instead of var, downcase and upcase instead of toUpperCase and toLowerCase, etc. A lot of this seems more like adjustment rather than improving efficiency, but I'm excited to see what ruby can do!

**Comment by jshawl** [comment]
:+1:
