### ISSUE TITLE
HW Preston Ruby

### ISSUE THREAD

**Issue by pdavies88** [ga-dc/try-ruby#28]
Something I found interesting was that when I multiple a string by a number in ruby it takes that string and iterates it x number of times. In JS multiplying a string by a number would yield a NaN result however ruby is able to compute them together even though they are different element types. Also you can call methods on a string in ruby where as in JS you would need to declare them as a variable first before calling that method. Also their a shortcuts in ruby to convert elements to strings, integers and arrays without running external functions such as toString or parsInt in JS.

**Comment by jshawl** [comment]
:+1:
