### ISSUE TITLE
Javascript vs Ruby Difference

### ISSUE THREAD

**Issue by ghost** [ga-dc/try-ruby#29]
In javascript, you would use something like the below to iterate through an array:

var arr = [1, 2, 3, 4];
for (var i = 0, len = arr.length; i < len; i++) {
    console.log(arr[i]);
}

In Ruby, the syntax is much shorter and logs each item with a puts command as opposed to a console.log. It takes much less syntax to iterate through an array. 

arr = [1, 2, 3, 4]
for item in arr
  puts item
end

**Comment by jshawl** [comment]
or `arr.each do |element|` :+1:
