### ISSUE TITLE
The JS-Ruby question

### ISSUE THREAD

**Issue by jkoul** [ga-dc/try-ruby#32]
Note: JS Ruby would be a fantastic name for a TV show detective.

More seriously, I can already tell Ruby is much more flexible than Javascript in managing and calling upon data. Its commands are cleaner and better-designed to work with a variety of potential inputs, which is necessary for core back-end systems engineering because Javascript is pretty brittle. For example, a simple "=" sign is sufficient to specify a variable, and the "var" precursor is unnecessary. The methods and commands are perhaps more intuitive as well, eg "to_i" vs. Javascript's "parseInt".

**Comment by jshawl** [comment]
:+1: I would totally watch that TV show!
