### ISSUE TITLE
syntax syntax syntax

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/try-ruby#34]
Seems to me the challenge with ruby will be learning the syntax.  All the concepts of programming are there as usual.  Many people observe that ruby is a "simpler" language (must less "wordy" than js).  That promises to be a good deal once ruby's way of doing things (syntax) is learned.  I have a library of javascript procedures built up that I can call on whenever facing a new WD challenge, and nothing for ruby -- yet.  (Actually I started up a library of loop samples from the excellent http://www.tutorialspoint.com/ tutorials collection.  I anticipate spending much time with that one...)  I like ruby's ability to string together methods via the "dot" connector.  

Comparisons (via tutorialspoint)
interesting option in ruby -- setting argument values for functions (via tutorialspoint):
`def method_name (var1=value1, var2=value2)
   expr..
end`
this looks useful for setting defaults that can be changed with a simple function call

something to watch out for -- variable numbers of arguments (parameters)
`def sample (*test)
    *** code ***
   end
end
sample "Zara", "6", "F"
sample "Mac", "36", "M", "MCA"`
using the "*" character this way will be something to get used to

classes -- yay!
`Class ClassName
{
   Number numberVariable1
   Number numberVariable2
   Characters stringVariable1
   Function functionName
   {
    *** code ***
   }
   Function driving
}`

**Comment by jshawl** [comment]
The `def sample (*test)` with variable arguments is somewhat uncommon. :+1:
