### ISSUE TITLE
"!" Reborn in Ruby

### ISSUE THREAD

**Issue by karldonus** [ga-dc/try-ruby#39]
Exclamation marks don't have as bad a rap in ruby. In JavaScript, a "!" indicates the opposite or "not" of a boolean, number, string, etc....whereas, it appears exclamation points have been reborn in ruby as a way of specifying current data, rather than making a copy. Honestly, I haven't totally grasped the importance of this...but I'm glad to see my punctuation friend has hired a rebranding firm to work on its image. Also, !'s friend the question mark has lent it's everyday connotation to make things, such as .include? more semantically sensical. With the "?", even a none programmer can guess that we're trying to find out if something is included rather than assigning the thing in question.

**Comment by jshawl** [comment]
! :+1: love that things ending in `?` always return true or false
