### ISSUE TITLE
ruby and js

### ISSUE THREAD

**Issue by MikeDulik** [ga-dc/try-ruby#41]
The ways to create a 'new' array object are different.

Ruby:
# instantiates new array with these values

myArray = [1,2,3]
# instantiates new array with name 'myArray' with values [3,2,1]

myArray.reverse
# doesn't create a new array, just changes the values of 'myArray' to [1,2,3]

myArray.reverse!

JS:
//declares and initializes array to [1,2,3]
var myArray = [1,2,3]
//changes values of array to [3,2,1]
myArray = {3,2,1]

**Comment by jshawl** [comment]
:+1:
