### ISSUE TITLE
Ruby vs Js

### ISSUE THREAD

**Issue by englep10** [ga-dc/try-ruby#42]
Ruby has a much shorter syntax that JS also Ruby has much larger library of methods that you can use as at you disposal. That means that you can call methods on variables/arrays/objects on these data types. That enables you to do more with less as well as not creating many functions in vanilla js, which would save a dev. a lot of time not building functions within their code. Ruby is a language that is designed to be easy to read and gives you much more flexibility when doing these projects.

**Comment by jshawl** [comment]
:+1:
