### ISSUE TITLE
Ruby Slippers

### ISSUE THREAD

**Issue by Curtismn87** [ga-dc/try-ruby#43]
The biggest difference for me in javascript and Ruby when it comes to complex data types are the hashs in ruby. I don't really understand exactly what is going on but whenever you enter commands in Ruby for the tutorial, they always refer to them as hashs. It's a different data type that javascript I don't think uses? or if it does we haven't used it, but in Ruby they refer to a lot of things as hashs.

**Comment by jshawl** [comment]
:+1: the ruby hash is _very_ similar to the JS object!
