### ISSUE TITLE
Ruby equality

### ISSUE THREAD

**Issue by puzzleboks** [ga-dc/try-ruby#45]
In Ruby one can test equality using ==, eql? and equal?. Each tests if two objects are exactly the same object. The == and eql? operator can be user defined, and can be used differently in different circumstances. I'm not sure I totally understand the differences.

In Javascript one can use either ==, or === to test equality. == can be used to test if things are 'mostly' true, whereas === is for strict equality

**Comment by jshawl** [comment]
:+1:
