### ISSUE TITLE
Try Ruby joe-gz

### ISSUE THREAD

**Issue by joe-gz** [ga-dc/try-ruby#47]
RUBY:
for i in "range" [do]
   COMMAND
end

JAVASCRIPT:
for (var i = 0; i <=10; i ++) {
 COMMAND
}

in ruby the basic for loop is much simpler.  it is essentially like writing out the english command of what you want done.  JS on the other hand you have to declare the variable, and the range is an equality, while the command is wrapped in curly brackets as well. If you used a "$" before the i, it would be a global variable instead of local

**Comment by nolds9** [comment]
:+1:
