### ISSUE TITLE
Conditionals

### ISSUE THREAD

**Issue by ebirving** [ga-dc/try-ruby#7]
Ruby seems to have a wider vocabulary for conditionals than Javascript does..
- Both have if/else statements, with the largest difference being on of syntax &ndash; Ruby uses `elsif` where JS uses the un-elided `else if`.
- For cases where `if/else` language might get unwieldy, Ruby's `case/when` statement is relatively analogous to JS's `switch` case, except that it's not tied to evaluating a single variable at a time. 
- I could not find a Javascript equivalent of Ruby's `unless` statement. Unless removes the need for `if !someCondition` ("if not someCondition") syntax.
- In Ruby, both `if` and `unless` can also be used as inline modifiers!

**Comment by jshawl** [comment]
:+1: So many options!!!
