### ISSUE TITLE
Ruby vs. JS - Functions

### ISSUE THREAD

**Issue by jball23** [ga-dc/try-ruby#76]
To create a function in Ruby you don't need curly braces or semicolons.  To create a function called say_hello, you would begin with def, then put the name of the function, then the argument, then the code block below, and when your code block is done, just put end.  

def say_hello(name)
   var = “Hello, ” + name
   return var
end

In javaScript, the same function would be written like so(and the function name would/should use camelCase instead of snake_case...

function sayHello(name) {
    var = "Hello, " + name;
    return var;
}

**Comment by adambray** [comment]
👍
