### ISSUE TITLE
JS vs Ruby - converting data

### ISSUE THREAD

**Issue by lelandjordon** [ga-dc/try-ruby#77]
Converting data between numbers and strings is less verbose in Ruby, but may make more sense as long as you remember the shorthand.

Ex in JS:
var num = 1776;
var year = num.toString();  <-- converts the numerical value 1776 to a string "1776"

in Ruby:
num = 1776
year = num.to_s      <-- does the same as above  ^^^

**Comment by andrewsunglaekim** [comment]
:+1:
