### ISSUE TITLE
ruby differences

### ISSUE THREAD

**Issue by petergcutler** [ga-dc/try-ruby#8]
The ".to_a" and ".to_i" syntax seems much more developer/developer's-fingers friendly than a lot of the JavaScript methods we've used so far. It seems like this syntax would let developers write code in a way that's much more fluid / less interruptive than in its JS counterpart. jquery/coffeescript probably help bridge this gap when you're more familiar with them, but I love the ease of this syntax. Looking forward to learning more.

**Comment by jshawl** [comment]
:+1: yes! ruby was designed with developers in mind.
