### ISSUE TITLE
Ruby vs. JS

### ISSUE THREAD

**Issue by mvaden** [ga-dc/try-ruby#80]
Ruby and Javascript are similar regarding their methods for fetching and printing certain types of data. Where they differ is in the return/printed data and the syntax for calling functions.
# ruby

<[0, 12, 23, 18, 3].length

> 5
# Javascript

<[0, 12, 23, 18, “pizza”].length

> 5
# 
# ruby

<“pizza” \* 6

> pizzapizzapizzapizza
# javascript

<“pizza” \* 6

> NaN
# 
# javascript

ticket = [12, 47, 35]
< ticket

> 12, 47, 35]
# ruby

ticket = [12, 47, 35]
< ticket 

> [12, 47, 35]

**Comment by tylercrosse** [comment]
:+1: Nice work!
