### ISSUE TITLE
Ruby vs JS- HabbyW

### ISSUE THREAD

**Issue by habbywhyte** [ga-dc/try-ruby#81]
One of the first differences I noticed was that variables are defined differently.  Javascript uses var to assign and save a value.  That is not necessary in Ruby.  Javascript (var name = "h") Ruby (name = "h")  Also, objects in Javascript are called hashes in Ruby and the key/value pair seems to be similar. The "key" in Ruby is sometimes referred to as "property" in javascript. ex.  Javascript( var person = { age: 20, gender: female, height: short} Ruby( person = { age: 20, gender: female, height: short}
to find value of key in Ruby-   person[:age]    to find value of key in javascript-   person.age

**Comment by adambray** [comment]
👍 Great answer!
