### ISSUE TITLE
Sorting method in Ruby and in JS

### ISSUE THREAD

**Issue by superbuggy** [ga-dc/try-ruby#82]
Ruby has an awesome built in sorting method, as does JS with 'Array' objects. Through making a typo I noticed that "sort!" and "sort" produced different result. The ! changes sort to a mutable method; if omitted, sort will return a sorted array but will not change the stored array. This syntactical feature/quirk feels pretty different from JS syntax.

**Comment by adambray** [comment]
Great point! I consider it a great feature that ruby often lets you choose to use a mutable / non-mutable variant of methods. 👍
