### ISSUE TITLE
JavaScript Vs Ruby Functions

### ISSUE THREAD

**Issue by hewity** [ga-dc/try-ruby#83]
Functions in JavaScripts are the same as methods in Ruby. The syntax of declaring a function Vs declaring a method is slightly different. 

For example in JavaScript it's -

function hello() {
  console.log("hello");
}

In Ruby the same logic can be written as -

def hello
  puts "hello"
end

Another thing I have noticed in Ruby is-
" " is  treated as true
0  is treated as true
[] is treated as true

**Comment by adambray** [comment]
👍
