### ISSUE TITLE
Ruby vs. Javascript Conditionals

### ISSUE THREAD

**Issue by JoshNezi** [ga-dc/try-ruby#84]
Ruby and Javascript conditionals seem to be the same, but the syntax is different. 

Ruby

name = "car"

if car == "Honda"
    puts "Drive Honda"
end

if name == ""Honda"
    puts "Drive Honda"
else
    puts "Drive Smart Car"
end</code>

Javascript 

name = "car"

if (car = Honda){
 console.log("This is a Honda")
} else {
 console.log("This is a Smart Car)
}

**Comment by andrewsunglaekim** [comment]
:+1:
