### ISSUE TITLE
Ruby vs JS - for loops

### ISSUE THREAD

**Issue by marygriffus** [ga-dc/try-ruby#85]
In Javascript a for loop takes the format:
`for (var i=0; i<n; i++) {console.log("what")}`
In Ruby the same for loop would take the form:
`for i in 1..n do puts "what" end` (or {puts "what"})
Both languages initialize a variable and iterate through a range of values, running a block of code each time. Ruby has several other ways to do the same basic thing, and Javascript has a couple alternate ways, too, but not quite as much flexibility.

**Comment by tylercrosse** [comment]
:+1:  Nice!
