### ISSUE TITLE
Functions - Ruby vs JS

### ISSUE THREAD

**Issue by msteffan** [ga-dc/try-ruby#9]
In Javascript, a function can be called with an expression or a declaration. A function expression would look like:
`function funcName(argument) {
// some chunk of code to execute
}`

In Ruby, however, there are several types of functions, one of which is a block. A block would be expressed as:

`def functionname(variable)
   return <value>
 end`

Javascript also has blocks, which are anonymous functions.

**Comment by jshawl** [comment]
:+1:
